spring:
  kafka:
    consumer:
      bootstrap-servers:  172.30.1.35:9092,:9092,172.30.1.59:9092,172.30.1.65:9092,172.30.1.80:9092,172.30.1.43:9092
      max-poll-records: 100
      max-poll-interval-ms: 300000
      auto-offset-reset: latest
      client-id: jaeshim-20220822
      topic: jaeshim-20220822
      group-id: jaeshim-20220822-group
      session-timeout-ms: 10000
    producer:
      bootstrap-servers: satbroker-02-kafka-dev-staturn:9092,satbroker-03-kafka-dev-staturn:9092
      acks: all

logging:
  level:
    root: DEBUG



